services:
  - type: web
    name: larizinha-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: CHANNEL_LINK
        sync: false
      - key: SUPPORT_LINK
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DB_PATH
        value: /data/larizinha.db
